<?php defined('PREVENT_DIRECT_ACCESS') OR exit('No direct script access allowed'); ?>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Products | Product Desk</title>
<style>:root{--ink:#17221f;--paper:#f4f0e8;--accent:#d9573f;--line:#c9c0b2}*{box-sizing:border-box}body{margin:0;color:var(--ink);background:radial-gradient(circle at 90% 0,#d9e3d0,transparent 30%),var(--paper);font-family:Georgia,serif}main{max-width:1100px;margin:auto;padding:28px 22px 64px}nav{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--line);padding-bottom:18px}nav a{color:var(--ink);text-decoration:none}.nav-actions{display:flex;gap:16px;align-items:center}.logout{border:0;background:none;text-decoration:underline;cursor:pointer;font:inherit;color:var(--ink)}.eyebrow{margin-top:70px;color:var(--accent);font:700 11px Verdana,sans-serif;letter-spacing:.16em;text-transform:uppercase}h1{font-size:clamp(3rem,8vw,6rem);line-height:.9;font-weight:400;margin:12px 0 14px}.intro{color:#46514c;font-size:18px}.toolbar{display:flex;justify-content:space-between;align-items:center;margin-top:38px;border-top:4px solid var(--ink);padding-top:18px}.button{background:var(--ink);color:#fffdf8;padding:12px 16px;text-decoration:none;font:700 13px Verdana,sans-serif}.notice{color:#33704b}.table-wrap{overflow-x:auto;margin-top:16px}table{width:100%;min-width:720px;border-collapse:collapse;text-align:left}th{padding:13px 10px;color:#58615c;font:700 10px Verdana,sans-serif;letter-spacing:.08em;text-transform:uppercase}td{padding:16px 10px;border-top:1px solid var(--line);font-size:16px}td:first-child{font-weight:700}.actions{white-space:nowrap}.actions a{margin-right:12px;color:var(--accent)}.delete{display:inline;border:0;padding:0;background:none;color:#a52d22;text-decoration:underline;cursor:pointer;font:inherit}@media(max-width:600px){main{padding-inline:18px}.eyebrow{margin-top:52px}.toolbar{align-items:flex-start;gap:14px}.toolbar h2{margin-top:0}}
</style></head><body><main>
<nav><a href="<?= base_url('products') ?>"><strong>Product Desk</strong></a><div class="nav-actions"><span><?= htmlspecialchars((string) ($_SESSION['username'] ?? ''), ENT_QUOTES, 'UTF-8') ?></span><form method="post" action="<?= base_url('logout') ?>"><button class="logout" type="submit">Log out</button></form></div></nav>
<div class="eyebrow">Authenticated inventory</div><h1>Products.</h1><p class="intro">A clear ledger of what is available, and what needs attention.</p>
<?php if ($message): ?><p class="notice">Product <?= htmlspecialchars($message, ENT_QUOTES, 'UTF-8') ?>.</p><?php endif; ?>
<div class="toolbar"><h2>All products</h2><a class="button" href="<?= base_url('products/create') ?>">+ Add product</a></div>
<div class="table-wrap"><table><thead><tr><th>Name</th><th>Description</th><th>Price</th><th>Quantity</th><th>Created</th><th>Actions</th></tr></thead><tbody>
<?php foreach ($products as $product): ?><tr><td><?= htmlspecialchars($product['product_name'], ENT_QUOTES, 'UTF-8') ?></td><td><?= htmlspecialchars($product['description'], ENT_QUOTES, 'UTF-8') ?></td><td>$<?= number_format((float) $product['price'], 2) ?></td><td><?= (int) $product['quantity'] ?></td><td><?= htmlspecialchars($product['created_at'], ENT_QUOTES, 'UTF-8') ?></td><td class="actions"><a href="<?= base_url('products/edit/' . (int) $product['id']) ?>">Edit</a><form class="delete" method="post" action="<?= base_url('products/delete/' . (int) $product['id']) ?>" onsubmit="return confirm('Delete this product?');"><button class="delete" type="submit">Delete</button></form></td></tr><?php endforeach; ?>
<?php if (!$products): ?><tr><td colspan="6">No products yet. Add the first one.</td></tr><?php endif; ?></tbody></table></div>
</main></body></html>